### PR TITLE
adding setup.py to pybasicbayes for distribution

### PR DESCRIPTION
**Pull request by yarden**
I converted pybasicbayes into standard python package format and wrote a ``setup.py`` for it. 

* Also made ``import`` statements more explicit. 
* Included some data files needed to run the examples as package data in ``setup.py``. 
* Declared the requirements in ``setup.py`` (hope that I didn't miss any.) Some scripts relied on ``moviepy``. I added a test for that but didn't include it as a requirement since it's not essential for the package.

A few scripts in the package didn't work for me (for reasons that don't have to do with the reorganization of the package), I noted them in ``notes_from_yk.txt``.

Once you look it over, it'd be great if you could register your package with ``pypi`` (https://pypi.python.org/pypi). You just make a username with them and then add your package them for distribution. You can make a source distribution by running:

``python setup.py sdist``

And you can register the package with:

``python setup.py register``

That'll enable people to install ``pybasicbayes`` with a simple one liner ``pip install pybasicbayes``, which in turn will make it possible for people to install ``pyhsmm`` in same way, and automatically get ``pybasicbayes`` and all the other dependencies.

Yarden

### CODE REVIEW

**Comment by yarden** [comment]
Please see latest repository -- I killed a problematic line that tried to read ``README.md``.

**Comment by mattjj** [comment]
This looks really fantastic.

Based on your most recent comment it sounds like you want to add a commit to the PR. Unfortunately I'm not sure how to do that when the PR comes from another repository (if there isn't some obvious button to edit the PR in GitHub's web interface... see anything?). I can just apply the change after merging.

To answer a question in your notes document, I have only used nose so I don't expect any unittest stuff to work. I should document the tests a little, but I run things like `nosetests -A regression` or `nosetests -A 'regression and not slow' --ipdb --ipdb-failures`.

**Comment by mattjj** [comment]
Thank you so much! I'll merge the other one soon.

**Comment by mattjj** [comment]
Oh yeah, regarding the demos not finishing. They call `pyplot.show()` at the end, which blocks execution until the figure windows are closed if the backend isn't pdf. Was it just waiting on figure windows?

**Comment by mattjj** [comment]
Oh and I was mistaken about that extra commit thing... looks like it was added to this PR after all! Edited my above comment.

**Pull request merged**
